blank_issues_enabled: false
contact_links:
  - name: Discord Server ğŸ—£ï¸
    url: https://discord.com/invite/7Jrm3AQ/
    about: Response times are substantially faster on Discord then on GitHub, consider asking there for help before opening an issue.
