blank_issues_enabled: false
contact_links:
  - name: Discord Server ğŸ—£ï¸
    url: https://getminiaturepets.com/discord
    about: Response times are substantially faster on Discord then on GitHub, consider asking there for help before opening an issue.
